//metal, plastic, non-recyclable, paper, food, glass, recycling center, clothing, rubber, wood
//Item material pairs
let i_m_pairs = {
  "coca cola can": ["metal"],
  "coffee capsule": ['plastic'],
  "aluminium plate": ["metal"],
  "aerosol can": ["metal"],
  "capsule": ['plastic'],
  "foil": ["metal"],
  "tray": ["metal","plastic"],
  "animal waste": ["non-recyclable"],
  "animal bedding": ["non-recyclable"],
  "bedding": ["non-recyclable"],
  "ash": ["non-recyclable"],
  "nappy": ["non-recyclable"],
  "baby wipe": ["non-recyclable"],
  "wipe": ["non-recyclable"],
  "baking tray": ["metal", "plastic"],
  "water bottle": ["metal", "plastic"],
  "sponge": ["non-recyclable"],
  "battery": ["metal"],
  "belt": ["metal"],
  "card": ["paper"],
  "blister package": ["non-recyclable"],
  "package": ["non-recyclable"],
  "packet": ["plastic"],
  "bone": ["food"],
  "book": ["paper"],
  "bread bag": ["non-recyclable"],
  "brochure": ["paper", "plastic"],
  "catalogue": ["paper", "plastic"],
  "paper": ["paper"],
  "plastic": ["plastic"],
  "broken glass": ["glass"],
  "glass": ["glass"],
  "metal": ["metal"],
  "bubble wrap": ["plastic"],
  "orange": ["food"],
  "teabag": ["paper"],
  "apple": ['food'],
  "beans": ['food'],
  "key": ["metal"],
  "gum": ['food'],
  'skirt': ['clothing'],
  "cigarette": ['paper'],
  'cigar': ['paper'],
  "berry": ['food'],
  "candle": ["non-recyclable"],
  "can": ["metal"],
  "cardboard": ["paper"],
  "carpet": ["recycling center"],
  "bag": ["plastic", "clothing", "non-recyclable"],
  "plastic bag": ["plastic"],
  "carton": ["paper"],
  "tetra pak": ["paper"],
  "litter": ["non-recyclable"],
  "CD": ["plastic"],
  "DVD": ["plastic"],
  "cellophane": ["non-recyclable"],
  "cereal bag": ["non-recyclable"],
  "bulb": ["glass"],
  "light bulb": ["glass"],
  "christmas tree light": ["glass", "metal", "plastic"],
  "light": ["glass", "metal", "plastic"],
  "cling film": ["non-recyclable"],
  "film": ["non-recyclable"],
  "clock": ["non-recyclable"],
  "clothes": ["clothing"],
  "coat hanger": ["non-recyclable"],
  "hanger": ["non-recyclable"],
  "coffee cup": ["glass", "metal"],
  "cup": ["glass", "metal", "plastic"],
  "children cup": ["plastic"],
  "coffee pod": ["non-recyclable"],
  "pod": ["non-recyclable"],
  "fat": ["non-recyclable"],
  "cooking oil": ["food"],
  "oil": ["food", "non-recyclable"],
  "coffee": ["food"],
  "cork": ["non-recyclable"],
  "cotton wool": ["non-recyclable"],
  "wool": ["non-recyclable"],
  "cotton bud": ["non-recyclable"],
  "bud": ["non-recyclable"],
  "crockery": ["metal"],
  "ceramic": ["non-recyclable"],
  "cutlery": ["metal"],
  "fork": ["metal"],
  "knife": ["metal"],
  "spoon": ["metal"],
  "pan": ["metal"],
  "pot": ["metal", "glass"],
  "plate": ["glass"],
  "dish": ["glass"],
  "crisp packet": ["non-recyclable"],
  "sweet wrapper": ["non-recyclable"],
  "crisp tube": ["non-recyclable"],
  "tube": ["plastic", "non-recyclable"],
  "cushion": ["recycling center"],
  "dental floss": ["non-recyclable"],
  "drink carton": ["paper"],
  "pillow": ["recycling center"],
  "drinking glass": ["glass"],
  "egg box": ["paper", "plastic"],
  "engine oil": ["non-recyclable"],
  "envelope": ["paper"],
  "elastic band": ["non-recyclable"],
  "band": ["non-recyclable"],
  "electrical appliances": ["metal", "plastic"],
  "electric cable": ["metal"],
  "cable": ["metal"],
  "electric blanket": ["plastic"],
  "blanket": ["plastic", "clothing"],
  "flat glass": ["glass"],
  "flower pot": ["glass"],
  "fruit": ["food"],
  "vegetable": ["food"],
  "food": ["food"],
  "waste": ["non-recyclable"],
  "chair": ["metal", "plastic", "wood"],
  "table": ['metal', 'plastic','wood'],
  "furniture": ["metal", "plastic", "wood"],
  "bottle": ["metal", "glass"],
  "jar": ['glass'],
  "gloves": ["rubber"],
  "greaseproof paper": ["paper"],
  "hair": ["non-recyclable"],
  "hat": ["clothing"],
  "pants": ["clothing"],
  "shoes": ["clothing"],
  "socks": ["clothing"],
  "jacket": ["clothing"],
  "dress": ["clothing"],
  "hand bag": ["clothing"],
  "hoover dust": ["non-recyclable"],
  "dust": ["non-recyclable"],
  "detergent": ["recycling center"],
  "soap": ["recycling center"],
  "garden chemical": ["recycling center"],
  "chemical": ["recycling center"],
  "ice-cream tub": ["plastic"],
  "tub": ["plastic"],
  "incontinence pad": ["non-recyclable"],
  "pad": ["non-recyclable"],
  "bandaid": ["non-recyclable"],
  "inflatable item": ["plastic"],
  "inhaler": ["non-recyclable"],
  "jar lid": ["plastic"],
  "lid": ["plastic", "glass"],
  "cloth": ["clothing"],
  "jiffy bag": ["non-recyclable"],
  "mail": ["paper"],
  "paper towel": ["non-recyclable"],
  "towel": ["clothing"],
  "toilet paper": ["non-recyclable"],
  "toilet": ["non-recyclable"],
  "keyboard": ["plastic", "metal"],
  "lamination": ["plastic"],
  "lamp": ["glass", "metal"],
  "laundry peg": ["plastic", "wood"],
  "peg": ["plastic", "wood"],
  "leather clothing": ["clothing"],
  "clothing": ["clothing"],
  "magazine": ["paper"],
  "margarine tub": ["plastic"],
  "mattress protector": ["non-recyclable"],
  "tennis racket": ["non-recyclable"],
  "table tennis racket": ["wood", "plastic"],
  "racket": ["non-recyclable"],
  "cricket bat": ["wood"],
  "bat": ["wood"],
  "football": ["rubber"],
  "tennis ball": ["rubber"],
  "basketball": ["rubber"],
  "golf ball": ["rubber"],
  "ball": ["rubber"],
  "table tennis ball": ["plastic"],
  "milk bottle": ["plastic"],
  "phone": ["recycling center"],
  "car battery": ['recycling center'],
  "bike battery": ["recycling center"],
  "battery": ["recycling center"],
  "nappy": ["non-recyclable"],
  "newspaper": ["paper"],
  "office paper": ["paper"],
  "peanut package": ["non-recyclable"],
  "papier mache": ["non-recyclable"],
  "mache": ["non-recyclable"],
  "pen": ["non-recyclable"],
  "pet food": ["non-recyclable"],
  "pet food package": ["non-recyclable"],
  "photograph": ["non-recyclable"],
  "photo": ["non-recyclable"],
  "pillow": ["recycling center"],
  "pizza box": ["paper"],
  "box": ['paper', "plastic"],
  "postcard": ["paper"],
  "polystyrene": ["plastic"],
  "pyrex": ["glass"],
  "razor blade": ["non-recyclable"],
  "blade": ["non-recyclable"],
  "rubber gloves": ["rubber"],
  "roll-on deoderant bottle": ["plastic"],
  "sanitary wear": ["non-recyclable"],
  "scarf": ["clothing"],
  "scrap metal": ["metal"],
  "soft toy": ["recycling center"],
  "toy": ["recycling center"],
  "styrofoam": ["non-recyclable"],
  "spectacles": ["glass"],
  "lens": ["glass"],
  "tablet package": ["non-recyclable"],
  "tea": ["food"],
  "mango": ["food"],
  "tea leaf": ["food"],
  "leaf": ["food"],
  "takeaway container": ["plastic"],
  "teddy bear": ["recycling center"],
  "teddy": ["recycling center"],
  "thermos flask": ["non-recyclable"],
  "flask": ["non-recyclable", "metal"],
  "tin": ["metal"],
  "tissue": ["non-recyclable"],
  "toothbrush": ["plastic"],
  "electric toothbrush": ["metal", "plastic"],
  "brush": ['plastic'],
  "toothpaste tube": ["non-recyclable"],
  "wallpaper": ["non-recyclable"],
  "washing powder bottle": ["plastic"],
  "wet wipe": ["non-recylable"],
  "watch": ["metal"],
  "yoghurt tub": ["plastic"]
}


export default i_m_pairs