//metal, plastic, non-recyclable, paper, food, glass, recycling center, clothing, rubber, wood
//Item material pairs
let i_m_pairs = {
  "coca cola can": ["metal"],
  "coffee capsule": ['plastic'],
  "aluminium plate": ["metal"],
  "aerosol can": ["metal"],
  "foil": ["metal"],
  "tray": ["metal","plastic"],
  "animal waste": ["non-recyclable"],
  "animal bedding": ["non-recyclable"],
  "ash": ["non-recyclable"],
  "nappies": ["non-recyclable"],
  "baby wipe": ["non-recyclable"],
  "baking tray": ["metal", "plastic"],
  "water bottle": ["metal", "plastic"],
  "sponge": ["non-recyclable"],
  "battery": ["metal"],
  "belt": ["metal"],
  "card": ["paper"],
  "blister pack": ["non-recyclable"],
  "bone": ["food"],
  "books": ["paper"],
  "bread bags": ["non-recyclable"],
  "brochure": ["paper", "plastic"],
  "catalogue": ["paper", "plastic"],
  "paper": ["paper"],
  "plastic": ["plastic"],
  "broken glass": ["glass"],
  "glass": ["glass"],
  "metal": ["metal"],
  "bubble wrap": ["plastic"],
  "candle": ["non-recyclable"],
  "can": ["metal"],
  "cardboard": ["paper"],
  "carpet": ["recycling center"],
  "plastic bag": ["plastic"],
  "carton": ["paper"],
  "tetra pak": ["paper"],
  "litter": ["non-recyclable"],
  "CD": ["plastic"],
  "DVD": ["plastic"],
  "cellophane": ["non-recyclable"],
  "cereal bag": ["non-recyclable"],
  "light bulb": ["glass"],
  "christmas tree lights": ["glass", "metal", "plastic"],
  "cling film": ["non-recyclable"],
  "clock": ["non-recyclable"],
  "clothes": ["clothing"],
  "coat hangers": ["non-recyclable"],
  "coffee cup": ["glass", "metal"],
  "cup": ["glass", "metal"],
  "children cup": ["plastic"],
  "coffee pod": ["non-recyclable"],
  "fat": ["non-recyclable"],
  "cooking oil": ["food"],
  "coffee ground": ["food"],
  "cork": ["non-recyclable"],
  "cotton wool": ["non-recyclable"],
  "cotton buds": ["non-recyclable"],
  "crockery": ["metal"],
  "ceramic": ["non-recyclable"],
  "cutlery": ["metal"],
  "fork": ["metal"],
  "knife": ["metal"],
  "spoon": ["metal"],
  "pan": ["metal"],
  "pot": ["metal"],
  "plate": ["glass"],
  "dish": ["glass"],
  "crisp packet": ["non-recyclable"],
  "sweet wrapper": ["non-recyclable"],
  "crisp tube": ["non-recyclable"],
  "cushion": ["recycling center"],
  "dental floss": ["non-recyclable"],
  "drink cartons": ["paper"],
  "pillow": ["recycling center"],
  "drinking glass": ["glass"],
  "egg box": ["paper", "plastic"],
  "engine oil": ["non-recyclable"],
  "envelope": ["paper"],
  "elastic band": ["non-recyclable"],
  "electrical appliances": ["metal", "plastic"],
  "electric cable": ["metal"],
  "electric blanket": ["plastic"],
  "flat glass": ["glass"],
  "flower pots": ["glass"],
  "fruit": ["food"],
  "vegetable": ["food"],
  "food waste": ["food"],
  "chair": ["metal", "plastic", "wood"],
  "table": ['metal', 'plastic','wood'],
  "furniture": ["metal", "plastic", "wood"],
  "bottle": ["metal", "glass"],
  "jar": ['glass'],
  "glove": ["rubber"],
  "greaseproof paper": ["paper"],
  "hair": ["non-recyclable"],
  "hat": ["clothing"],
  "pant": ["clothing"],
  "shoe": ["clothing"],
  "sock": ["clothing"],
  "jacket": ["clothing"],
  "dress": ["clothing"],
  "handbag": ["clothing"],
  "hoover dust": ["non-recyclable"],
  "detergent": ["recycling center"],
  "garden chemical": ["recycling center"],
  "ice-cream tub": ["plastic"],
  "tub": ["plastic"],
  "incontinence pad": ["non-recyclable"],
  "bandaid": ["non-recyclable"],
  "inflatable item": ["plastic"],
  "inhaler": ["non-recyclable"],
  "jar lid": ["plastic"],
  "cloth": ["clothing"],
  "jiffy bag": ["non-recyclable"],
  "mail": ["paper"],
  "paper tower": ["non-recyclable"],
  "toilet paper": ["non-recyclable"],
  "keyboard": ["plastic", "metal"],
  "lamination": ["plastic"],
  "lamp": ["glass", "metal"],
  "laundry peg": ["plastic", "wood"],
  "leather clothing": ["clothing"],
  "magazine": ["paper"],
  "margarine tub": ["plastic"],
  "mattress protector": ["non-recyclable"],
  "tennis racket": ["non-recyclable"],
  "table tennis racket": ["wood", "plastic"],
  "cricket bat": ["wood"],
  "football": ["rubber"],
  "tennis ball": ["rubber"],
  "basketball": ["rubber"],
  "golf ball": ["rubber"],
  "ball": ["rubber"],
  "table tennis ball": ["plastic"],
  "milk bottle": ["plastic"],
  "phone": ["recycling center"],
  "car battery": ['recycling center'],
  "bike battery": ["recycling center"],
  "nappy": ["non-recyclable"],
  "newspaper": ["paper"],
  "office paper": ["paper"],
  "peanut packaging": ["non-recyclable"],
  "papier mache": ["non-recyclable"],
  "pen": ["non-recyclable"],
  "pet food": ["non-recyclable"],
  "pet food packaging": ["non-recyclable"],
  "photograph": ["non-recyclable"],
  "pillow": ["recycling center"],
  "pizza box": ["paper"],
  "postcard": ["paper"],
  "polystyrene": ["plastic"],
  "pyrex": ["glass"],
  "razor blade": ["non-recyclable"],
  "rubber gloves": ["rubber"],
  "roll-on deoderant bottle": ["plastic"],
  "sanitary wear": ["non-recyclable"],
  "scarf": ["clothing"],
  "scrap metal": ["metal"],
  "soft toy": ["recycling center"],
  "styrofoam": ["non-recyclable"],
  "spectacles": ["glass"],
  "tablet packing": ["non-recyclable"],
  "tea bag": ["food"],
  "tea leaf": ["food"],
  "takeaway container": ["plastic"],
  "teddy bear": ["recycling center"],
  "thermos flask": ["non-recyclable"],
  "tin": ["metal"],
  "tissue": ["non-recyclable"],
  "toothbrush": ["plastic"],
  "electric toothbrush": ["metal", "plastic"],
  "toothpaste tube": ["non-recyclable"],
  "wallpaper": ["non-recyclable"],
  "washing powder bottle": ["plastic"],
  "wet wipe": ["non-recylable"],
  "watches": ["metal"],
  "yoghurt tub": ["plastic"]



}


export default i_m_pairs